# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

        # Setup Flutter environment
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 'stable'

        # Install dependencies
      - name: Install Flutter dependencies
        run: flutter pub get

        # Run Flutter analyze
      - name: Analyze project source
        run: flutter analyze

        # Run tests
      - name: Run tests
        run: flutter test
